#!/bin/sh
export XDG_RUNTIME_DIR=/run/user/0
export WAYLAND_DISPLAY=wayland-1

riverctl keyboard-layout -options "" us

riverctl map normal Super Q close
riverctl map normal Super+Shift E exit

riverctl map normal Super Return spawn foot
riverctl map normal Super C spawn "chromium --ozone-platform=wayland --no-sandbox --test-type"
riverctl map normal Super S spawn "foot -e /bin/sh"

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super H focus-column left
riverctl map normal Super L focus-column right
riverctl map normal Super+Shift H move left
riverctl map normal Super+Shift L move right

for i in $(seq 1 9); do
  tags=$((1 << ($i - 1)))
  riverctl map normal Super $i set-focused-tags $tags
  riverctl map normal Super+Shift $i set-view-tags $tags
  riverctl map normal Super+Control $i toggle-focused-tags $tags
  riverctl map normal Super+Alt $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

riverctl map normal Super+Shift Return zoom

riverctl map normal Super Space toggle-float
riverctl map normal Super F toggle-fullscreen

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

foot &
