# Open-source GPU stack used by the desktop profile.
CONFIG_DRM=y
CONFIG_DRM_ATOMIC=y
CONFIG_DRM_I915=y
CONFIG_DRM_AMDGPU=y
CONFIG_DRM_RADEON=y
CONFIG_DRM_VIRTIO_GPU=y
CONFIG_DRM_VIRTIO_GPU_COHERENT=y
CONFIG_DRM_VMWGFX=y
CONFIG_DRM_VMWGFX_FBC=y
CONFIG_HYPERVISOR_GUEST=y
CONFIG_VMWARE_VMCI=y
CONFIG_VBOXGUEST=m
